name: notibox
version: 0.0.1-alpha
publish_to: none
description: Inbox app for Notion.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  flutter_easyloading: ^3.0.0
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_native_splash: ^1.2.0
  get: 4.1.4
  url_launcher: ^6.0.8
  intl: ^0.17.0
  internet_connection_checker: ^0.0.1+1
  dio_cache_interceptor: ^3.0.1  
  open_settings: ^2.0.1
  dio_cache_interceptor_hive_store: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  shimmer: ^2.0.0
  awesome_notifications: ^0.0.6+9

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.6

flutter: 
  assets: 
    - assets/images/
    - assets/logo/
  uses-material-design: true

